fox_knows/urls.py
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', home_page_views.index),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', home_page_views.index),
        ])),

        url(r'^links/', include([
            url(r'^$', feed_views.links),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', feed_views.links),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', feed_views.links),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', feed_views.links),
        ])),

        url(r'^organizations/', include([
            url(r'^$', feed_views.organizations),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', feed_views.organizations),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', feed_views.organizations),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', feed_views.organizations),
        ])),

        url(r'^persons/', include([
            url(r'^$', feed_views.persons),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', feed_views.persons),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', feed_views.persons),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', feed_views.persons),
        ])),

        url(r'^dance-styles/', include([
            url(r'^$', feed_views.dance_styles),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', feed_views.dance_styles),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', feed_views.dance_styles),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', feed_views.dance_styles),

        ])),

        url(r'^$', RedirectView.as_view(pattern_name='feed_articles', permanent=True)),
        url(r'^(?:direction-(?P<direction_title>[\w-]+)/)', include([
            url(r'^$', RedirectView.as_view(pattern_name='feed_articles_direction', permanent=True)),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)$',
                RedirectView.as_view(pattern_name='feed_articles_direction_city', permanent=True)),
        ])),
        url(r'^(?:city-(?P<city_title>[\w-]+)/)?$',
            RedirectView.as_view(pattern_name='feed_articles_city', permanent=True)),

    ])),

    url(r'^map/', include([
        url(r'^places/', include([
            url(r'^$', map_views.places, name='map_places'),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', map_views.places, name='map_places_direction'),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.places,
                    name='map_places_direction_city'),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.places,
                name='map_places_city'),
        ])),

        url(r'^schools/', include([
            url(r'^$', map_views.schools, name='map_schools'),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', map_views.schools, name='map_schools_direction'),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.schools,
                    name='map_schools_direction_city'),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.schools,
                name='map_schools_city'),
        ])),

        url(r'^shops/', include([
            url(r'^$', map_views.shops, name='map_shops'),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', map_views.shops, name='map_shops_direction'),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.shops,
                    name='map_shops_direction_city'),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.shops,
                name='map_shops_city'),
        ])),

        url(r'^services/', include([
            url(r'^$', map_views.services, name='map_services'),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', map_views.services, name='map_services_direction'),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.services,
                    name='map_services_direction_city'),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.services,
                name='map_services_city'),
        ])),

        url(r'^halls/', include([
            url(r'^$', map_views.halls, name='map_halls'),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', map_views.halls, name='map_halls_direction'),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.halls,
                    name='map_halls_direction_city'),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', map_views.halls,
                name='map_halls_city'),
        ])),

        url(r'^$', RedirectView.as_view(pattern_name='map_places', permanent=True)),
        url(r'^(?:direction-(?P<direction_title>[\w-]+)/)', include([
            url(r'^$', RedirectView.as_view(pattern_name='map_places_direction', permanent=True)),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)$',
                RedirectView.as_view(pattern_name='map_places_direction_city', permanent=True)),
        ])),
        url(r'^(?:city-(?P<city_title>[\w-]+)/)?$',
            RedirectView.as_view(pattern_name='map_places_city', permanent=True)),
    ])),

    url(r'^events/', include([
        url(r'^upcoming/', include([
            url(r'^$', events_views.upcoming, name='events_upcoming'),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', events_views.upcoming, name='events_upcoming_direction'),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', events_views.upcoming,
                    name='events_upcoming_direction_city'),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', events_views.upcoming,
                name='events_upcoming_city'),
        ])),

        url(r'^calendar/', include([
            url(r'^$', home_page_views.index),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', home_page_views.index),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', home_page_views.index),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', home_page_views.index),
        ])),

        url(r'^promo-actions/', include([
            url(r'^$', home_page_views.index),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', home_page_views.index),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', home_page_views.index),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', home_page_views.index),
        ])),

        url(r'^past/', include([
            url(r'^$', events_views.past),
            url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
                url(r'^$', events_views.past),
                url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', events_views.past),
            ])),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', events_views.past),
        ])),

        url(r'^$', RedirectView.as_view(pattern_name='events_upcoming', permanent=True)),
        url(r'^(?:direction-(?P<direction_title>[\w-]+)/)', include([
            url(r'^$', RedirectView.as_view(pattern_name='events_upcoming_direction', permanent=True)),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)$',
                RedirectView.as_view(pattern_name='events_upcoming_direction_city', permanent=True)),
        ])),
        url(r'^(?:city-(?P<city_title>[\w-]+)/)?$',
            RedirectView.as_view(pattern_name='events_upcoming_city', permanent=True)),

    ])),

    url(r'^ratings/', include([
        url(r'^$', home_page_views.index),
        url(r'^(?:direction-(?P<direction_title>[\w-]+)/)?', include([
            url(r'^$', RedirectView.as_view(url='upcoming', permanent=True)),
            url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', home_page_views.index),
        ])),
        url(r'^(?:city-(?P<city_title>[\w-]+)/)?$', home_page_views.index),
    ])),

    # url(r'^profiles/', include([
    #     url(r'^$', RedirectView.as_view(pattern_name='profiles_profile', permanent=True)),
    #     url(r'^(?:direction-(?P<direction_title>[\w-]+)/)', include([
    #         url(r'^$', RedirectView.as_view(pattern_name='profiles_profile_direction', permanent=True)),
    #         url(r'^(?:city-(?P<city_title>[\w-]+)/)$',
    #             RedirectView.as_view(pattern_name='profiles_profile_direction_city', permanent=True)),
    #     ])),
    #     url(r'^(?:city-(?P<city_title>[\w-]+)/)?$',
    #         RedirectView.as_view(pattern_name='profiles_profile_city', permanent=True)),
    # ])),

    url(r'^create/', include([
        url(r'^$', create_views.show_create_page),
        url(r'^(?P<instance>[\w-]+)/$', create_views.create_instance),
    ])),

    url(r'^profile-(?P<instance_id>\d+)/settings/$', profiles_views.settings),

    url(r'^(?P<entity>[\w-]+)-(?P<instance_id>\d+)/', include([
        url(r'^$', common_views.instance_page),
        url(r'^edit/', include([
            url(r'^$', common_views.edit_instance_page),
            url(r'^(?P<attribute>[\w-]+)/$', common_views.edit_instance_attr),
        ])),
        url(r'^delete/$', common_views.delete_instance),
        url(r'^create-(?P<attribute>[\w-]+)/$', common_views.create_attr),

        url(r'^(?P<attribute>[\w-]+)-(?P<attribute_id>\d+)/', include([
            # url(r'^edit/$', common_views.edit_attr),
            # url(r'^delete/$', common_views.delete_attr),
        ])),
    ])),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \

entities/models/locations.py
from django.db import models

from entities.models.classes import City
from entities.models.userprofile import UserProfile


class AbstractMapCoordinates(models.Model):
    lat = models.CharField(max_length=20)
    lng = models.CharField(max_length=20)

    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return 'Lat:%s, lng: %s' % (self.lat, self.lng)

    class Meta:
        ordering = ('created',)
        abstract = True


class PlaceMapCoordinates(AbstractMapCoordinates):
    def __str__(self):
        if hasattr(self, 'placelocation'):
            return 'Place: %s - Lat:%s, lng: %s' % (self.placelocation.place_set.all(), self.lat, self.lng)
        return 'Place: Lat:%s, lng: %s' % (self.lat, self.lng)


class SchoolMapCoordinates(AbstractMapCoordinates):
    def __str__(self):
        if hasattr(self, 'schoollocation'):
            return 'School: %s - Lat:%s, lng: %s' % (self.schoollocation.school_set.all(), self.lat, self.lng)
        return 'School: Lat:%s, lng: %s' % (self.lat, self.lng)


class OrganizationMapCoordinates(AbstractMapCoordinates):
    def __str__(self):
        if hasattr(self, 'organizationlocation'):
            return 'Organization: %s - Lat:%s, lng: %s' % (self.organizationlocation.organization_set.all(),
                                                           self.lat, self.lng)
        return 'Organization: Lat:%s, lng: %s' % (self.lat, self.lng)


class ShopMapCoordinates(AbstractMapCoordinates):
    def __str__(self):
        if hasattr(self, 'shoplocation'):
            return 'Shop: %s - Lat:%s, lng: %s' % (self.shoplocation.shop_set.all(), self.lat, self.lng)
        return 'Shop: Lat:%s, lng: %s' % (self.lat, self.lng)


class CustomerServicesMapCoordinates(AbstractMapCoordinates):
    def __str__(self):
        if hasattr(self, 'customerserviceslocation'):
            return 'CustomerServices: %s - Lat:%s, lng: %s' % (self.customerserviceslocation.shop_set.all(),
                                                               self.lat, self.lng)
        return 'CustomerServices: Lat:%s, lng: %s' % (self.lat, self.lng)


class HallMapCoordinates(AbstractMapCoordinates):
    def __str__(self):
        if hasattr(self, 'halllocation'):
            return 'Hall: %s - Lat:%s, lng: %s' % (self.halllocation.hall_set.all(), self.lat, self.lng)
        return 'Hall: Lat:%s, lng: %s' % (self.lat, self.lng)


class AbstractLocation(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    address = models.CharField(max_length=100, blank=True)
    note = models.CharField(max_length=100, blank=True)

    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        if self.address:
            return '%s, %s by %s' % (self.city.title, self.address, self.author)
        return '%s by %s' % (self.city.title, self.author)

    def title_show(self):
        if self.address:
            return '%s, %s' % (self.address, self.city.title)
        return '%s' % (self.city.title,)

    class Meta:
        ordering = ('created',)
        abstract = True


class EventLocation(AbstractLocation):
    pass


class PlaceLocation(AbstractLocation):
    coordinates = models.OneToOneField(PlaceMapCoordinates, on_delete=models.CASCADE, blank=True, null=True)


class SchoolLocation(AbstractLocation):
    coordinates = models.OneToOneField(SchoolMapCoordinates, on_delete=models.CASCADE, blank=True, null=True)


class OrganizationLocation(AbstractLocation):
    coordinates = models.OneToOneField(OrganizationMapCoordinates, on_delete=models.CASCADE, blank=True, null=True)


class ShopLocation(AbstractLocation):
    coordinates = models.OneToOneField(ShopMapCoordinates, on_delete=models.CASCADE, blank=True, null=True)


class CustomerServicesLocation(AbstractLocation):
    coordinates = models.OneToOneField(CustomerServicesMapCoordinates, on_delete=models.CASCADE, blank=True, null=True)


class HallLocation(AbstractLocation):
    coordinates = models.OneToOneField(HallMapCoordinates, on_delete=models.CASCADE, blank=True, null=True)

entities/forms/classes.py
# coding: utf-8

from django import forms

from entities.models import AbstractClass
from entities.models import AbstractGlobalClass
from entities.models import AbstractLocalClass
from entities.models import City
from entities.models import DanceDirectionClass
from entities.models import DanceStyleClass
from entities.models import Direction


class AbstractClassForm(forms.ModelForm):
    class Meta:
        model = AbstractClass
        fields = ['title']


class AbstractGlobalClassForm(forms.ModelForm):
    class Meta:
        model = AbstractGlobalClass
        fields = ['title']


class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ['title']


class SelectCityForm(forms.Form):
    city = forms.ChoiceField(label="", widget=forms.Select(attrs={'onChange': 'city_direction.submit();',
                                                                  'style': 'min-width: 172px; width: 50%;',
                                                                  'tabindex': '0'}))

    def __init__(self, *args, **kwargs):
        cities = City.objects.all()
        city_choices = [(city.id, city.title) for city in cities]
        city_choices.insert(0, (0, 'Все города'))
        super(SelectCityForm, self).__init__(*args, **kwargs)
        self.fields['city'].choices = city_choices


class DirectionForm(forms.ModelForm):
    class Meta:
        model = Direction
        fields = ['title']


class SelectDirectionForm(forms.Form):
    direction = forms.ChoiceField(label="", widget=forms.Select(attrs={'onChange': 'city_direction.submit();',
                                                                       'style': 'min-width: 172px; width: 50%;',
                                                                       'tabindex': '0'}))

    def __init__(self, *args, **kwargs):
        directions = Direction.objects.all()
        direction_choices = [(direction.id, direction.title) for direction in directions]
        direction_choices.insert(0, (0, 'Все направления'))
        super(SelectDirectionForm, self).__init__(*args, **kwargs)
        self.fields['direction'].choices = direction_choices


class AbstractLocalClassForm(forms.ModelForm):
    class Meta:
        model = AbstractLocalClass
        fields = ['title', 'directions']


class DanceDirectionClassForm(forms.ModelForm):
    class Meta:
        model = DanceDirectionClass
        fields = ['title', 'directions']


class DanceStyleClassForm(forms.ModelForm):
    class Meta:
        model = DanceStyleClass
        fields = ['title', 'directions', 'dance_direction']

templates/atropos/entities/album/album-edit.html
{% extends "base.html" %}

{% block title %}{{ title }} - {% endblock %}

{% block wrapper %}
{% include 'modal-style.html' %}
		<!-- WRAPPER -->
		<div id="wrapper" style="padding-top:0">
			<div class="container magazine top-no-header" style="padding-top:20px">
				<div class="row">
					<div class="col-md-12">

						<header class="page-title">
							<h1 style="text-align: center">{{ instance.title }}</h1>
							<a href="/album-{{ instance.pk }}/" class="btn btn-primary">Просмотреть изменения</a>
						</header>

						<div class="divider half-margins"><!-- divider -->
							<i class="fa fa-star"></i>
						</div>
					</div>
				</div>
			</div>

			<section class="container">
				<div class="row">

					<div class="col-md-9">
						<div class="white-row">

							<h3 class="page-header margin-bottom40" style="text-align:center">
								<strong class="styleColor">Основная информация</strong>
							</h3>

							<div class="row">
								<!-- col 1 -->
								<div class="col-md-5 col-sm-6 col-md-offset-1">
									{% if instance.types.all %}
									<div class="row">
										<div class="col-md-12">
											<small class="block styleCoor fsize20">
												<i class="fa fa-list-alt" title="Типы мероприятий"></i>
												{% for instance_type in instance.types.all %}
												<span class="label label-primary" title="Тип мероприятия">{{ instance_type.title_show }}</span>
												{% endfor %}
											</small>
										</div>
									</div>
									{% endif %}
									{% if instance.local_classes.dance_styles.all %}
									<div class="row">
										<div class="col-md-12">
											<small class="block styleCoor fsize20">
												<i class="fa fa-reorder" title="Стиль танца"></i>
												{% for dance_style in instance.local_classes.dance_styles.all %}
												<span class="label label-success" title="Стиль танца">{{ dance_style.title }}</span>
												{% endfor %}
											</small>
										</div>
									</div>
									{% endif %}
								</div>
								<!-- col 2 -->
								<div class="col-md-5 col-sm-6 col-md-offset-1">
									{% if instance.locations.all %}
									<div class="row">
										<div class="col-md-12">
											<small class="block styleCoor fsize20">
												<i class="fa fa-globe" title="Места проведения"></i>
												{% for location in instance.locations.all %}
												<span class="label label-info" title="Место проведения">{{ location.title_show }}</span>
												{% endfor %}
											</small>
										</div>
									</div>
									{% endif %}
									{% if instance.note %}
									<div class="row">
										<div class="col-md-12">
											<small class="block styleCoor fsize20">
												<i class="fa fa-exclamation-circle" title="Обратите внимание"></i>
												<span class="label label-default" title="Обратите внимание">{{ instance.note }}</span>
											</small>
										</div>
									</div>
									{% endif %}
								</div>
							</div>

							<hr style="margin: 20px 0"/><!-- divider -->

							{% if instance.image %}
							<div class="row">
								<div class="col-md-10 col-md-offset-1" style="margin-bottom: 10px; text-align: left;">
									<img src="{{ instance.image.url }}" class="img-responsive" style="width: 100%; height: auto; display: block; margin-bottom: 10px;">
								</div>
							</div>
							<hr style="margin: 20px 0"/><!-- divider -->
							{% endif %}

							{% if instance.description %}
							<p class="lead text-center">Описание</p>
							{{ instance.description|linebreaks }}
							{% endif %}

							{% if instance.links.all %}
							<p>Источник:
								{% for link in instance.links.all %}
								<a href="{{ link.link }}">Перейти</a>
								{% endfor %}
							</p>
							{% endif %}

							{% if instance.video %}
							<div class="row">
								<div class="col-md-10 col-md-offset-1">
									<div style="width: 100%; position: relative; padding: 0;">
										<iframe src="{{ instance.video }}" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0; margin: 0; padding: 0;" width="800" height="450"></iframe>
									</div>
								</div>
							</div>
							{% endif %}
						</div><!-- /.white-row -->
					</div>

					<!-- side column -->
					<div class="col-md-3">
						<div class="white-row">
							<h3 class="page-header nomargin-top margin-bottom40">
								Изменить <strong class="styleColor">информацию</strong>
							</h3>
							<div class="row">
								<div class="form-group">
									<div class="col-md-12 col-sm-6">

										{% for url_entity, url_attr, title in edit_buttons %}
										<a data-toggle="modal" href="/{{ url_entity }}-{{ instance.pk }}/edit/{{ url_attr }}/"
										   data-target="#myModal" class="btn btn-primary">{{ title }}</a>
										<br />
										{% endfor %}

										<!-- Modal -->
										<div id="myModal" class="modal fade" role="dialog">
											<div class="modal-dialog">
												<div class="modal-content clearable-content">
												</div>
										  	</div>
										</div>

										<!-- Modal -->
										<div id="myModal2" class="modal fade" role="dialog">
											<div class="modal-dialog">
											  	<div class="modal-content clearable-content">
											  	</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
		<!-- /WRAPPER -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script>
$(document).on('hidden.bs.modal', function (e) {
    var target = $(e.target);
    target.removeData('bs.modal')
    .find(".clearable-content").html('');
});
</script>
{% endblock %}

templates/atropos/entities/album/album-single.html
{% extends "base.html" %}
{% load can_edit %}
{% load can_delete %}
{% load get_direction_city_url %}

{% block title %}{{ title }} - {% endblock %}

{% block wrapper %}
{% include 'modal-style.html' %}
		<!-- WRAPPER -->
		<div id="wrapper" style="padding-top:0">
			<div class="container magazine top-no-header" style="padding-top:20px">
				<div class="row">
					<div class="col-md-12">
						<header class="page-title">
							<h1 style="text-align: center">{{ instance.title }}</h1>
							<a href="/feed/albums/" class="btn btn-primary">Список альбомов</a>
							{% if user|can_edit:instance %}<a href="{{ request.path }}edit/" class="btn btn-primary">Изменить</a> {% endif %}
							{% if user|can_delete:instance %}<a class="btn btn-danger" data-toggle="modal" data-target="#deleteModal">Удалить</a>{% endif %}
						</header>

						{% include 'entities/instance-delete.html' %}

						<div class="divider half-margins"><!-- divider -->
							<i class="fa fa-star"></i>
						</div>
					</div>
				</div>
			</div>

			<section class="container">
				<div class="row">

					<div class="col-md-9">
						<div class="white-row">

							<h3 class="page-header margin-bottom40" style="text-align:center">
								<strong class="styleColor">Основная информация</strong>
							</h3>

							<div class="row">
								<!-- col 1 -->
								<div class="col-md-5 col-sm-6 col-md-offset-1">
									{% if instance.types.all %}
									<div class="row">
										<div class="col-md-12">
											<small class="block styleCoor fsize20">
												<i class="fa fa-list-alt" title="Типы мероприятий"></i>
												{% for instance_type in instance.types.all %}
												<span class="label label-primary" title="Тип мероприятия">{{ instance_type.title_show }}</span>
												{% endfor %}
											</small>
										</div>
									</div>
									{% endif %}
								</div>
								<!-- col 2 -->
								<div class="col-md-5 col-sm-6 col-md-offset-1">
									{% if instance.locations.all %}
									<div class="row">
										<div class="col-md-12">
											<small class="block styleCoor fsize20">
												<i class="fa fa-globe" title="Места проведения"></i>
												{% for location in instance.locations.all %}
												<span class="label label-info" title="Место проведения">{{ location.title_show }}</span>
												{% endfor %}
											</small>
										</div>
									</div>
									{% endif %}
									{% if instance.note %}
									<div class="row">
										<div class="col-md-12">
											<small class="block styleCoor fsize20">
												<i class="fa fa-exclamation-circle" title="Обратите внимание"></i>
												<span class="label label-default" title="Обратите внимание">{{ instance.note }}</span>
											</small>
										</div>
									</div>
									{% endif %}
								</div>
							</div>

							<hr style="margin: 20px 0"/><!-- divider -->

							{% if instance.image %}
							<div class="row">
								<div class="col-md-10 col-md-offset-1" style="margin-bottom: 10px; text-align: left;">
									<img src="{{ instance.image.url }}" class="img-responsive" style="width: 100%; height: auto; display: block; margin-bottom: 10px;">
								</div>
							</div>
							<hr style="margin: 20px 0"/><!-- divider -->
							{% endif %}

							{% if instance.description %}
							<p class="lead text-center">Описание места</p>
							{{ instance.description|linebreaks }}
							{% endif %}

							{% if instance.links.all %}
							<p>Источник:
								{% for link in instance.links.all %}
								<a href="{{ link.link }}">Перейти</a>
								{% endfor %}
							</p>
							{% endif %}

							{% if instance.video %}
							<div class="row">
								<div class="col-md-10 col-md-offset-1">
									<div style="width: 100%; position: relative; padding: 0;">
										<iframe src="{{ instance.video }}" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0; margin: 0; padding: 0;" width="800" height="450"></iframe>
									</div>
								</div>
							</div>
							{% endif %}
						</div><!-- /.white-row -->
					</div>

					<!-- side column -->
					<div class="col-md-3">
						<form method="post" class="white-row" action="/map/shops/{{ request.session|get_direction_city_url }}">
							{% csrf_token %}
							<!-- FILTER / SEARCH -->
							<h3 class="page-header nomargin-top margin-bottom40">
								Найти <strong class="styleColor">магазины</strong>
							</h3>

							<div class="row">
								<div class="form-group">

									<!--<div class="col-md-12 col-sm-6">
										<label>{{ form.city.label }}</label>
										<select class="chosen-select" data-placeholder="Выберите города..." id="id_city" name="city" style="min-width: 172px; width: 100%;" tabindex="0" required="">
											{% for x,y in form.fields.city.choices %}
												<option value="{{ x }}" {% if x == city_num %} selected{% endif %}>{{ y }}</option>
											{% endfor %}
										</select>
									</div>-->

									{% for field in form %}
									<div class="col-md-12 col-sm-6">
										<label>{{ field.label }}</label>
										{{ field }}
									</div>
									{% endfor %}

									<div class="col-md-12">
										<label>&nbsp;</label>
										<button class="btn btn-primary fullwidth">Найти</button>
									</div>
								</div>
							</div>
						</form>
						<!-- SOCIALS -->
						<h3 class="page-header">
							<i class="fa fa-twitter"></i>
							<strong class="styleColor">Следите</strong> за нами
						</h3>
						<a href="#" class="social fa fa-facebook"></a>
						<a href="#" class="social fa fa-twitter"></a>
						<a href="#" class="social fa fa-google-plus"></a>
						<a href="#" class="social fa fa-linkedin"></a>
						<a href="#" class="social fa fa-pinterest"></a>
						<a href="#" class="social fa fa-flickr"></a>
					</div>
				</div>
			</section>
		</div>
		<!-- /WRAPPER -->
{% endblock %}